settings:

  # list of objects to be rendered
  objects:
    example:
      # object file
      file: "resources/models/maca2.byu"
      # object scale, default is 1
      scale: 0.1
      # object position
      position:
        - 1.5
        - -20.2
        - -80.5