settings:

  # list of objects to be rendered
  objects:
    example:
      # object file
      file: "resources/models/calice2.byu"
      # object scale, default is 1
      scale: 0.1
      # object position
      position:
        - -25.5
        - 20.2
        - -90.5
    example2:
      # object file
      file: "resources/models/vaso.byu"
      # object scale, default is 1
      scale: 0.1
      # object position
      position:
        - 1.5
        - 20.2
        - -80.5