settings:

  # list of objects to be rendered
  objects:
    example:
      # object file
      file: "resources/models/maca.byu"
      # object scale, default is 1
      scale: 0.1
      # object position
      position: [-25.5 ,20.2 ,-90.5]
      # rgba values of each material color, [0 ~ 1]
      material:
        ambient: [1.0, 0.5, 0.31, 1.0]
        diffuse: [1.0 ,0.5 ,0.31 ,1.0]
        specular: [0.5 ,0.5 ,0.5 ,1.0]
        shininess: 32
  
    example2:
      file: "resources/models/vaso.byu"
      scale: 0.1
      position: [1.5 ,20.2 ,-80.5]
      material:
        ambient: [0.2 ,0.2 ,0.2 ,1.0]
        diffuse: [0.7 ,0.5 ,0.8 ,1.0]
        specular: [0.5 ,0.5 ,0.5 ,1.0]
        shininess: 100