settings:
  light:
    position: [0, 500, 200]
    ambient: [0.4, 0.4, 0.4, 1.0]
    diffuse: [0.5, 0.85, 1.0, 1.0]
    specular: [0.5, 0.55, 1.0, 1.0]
  
  camera:
    position: [-50, 400, 550]
    fovy: 45
    near: 5
    far: 10000
    speed: 100
    yaw: -90
    pitch: -25

  misc:
    show_floor: true
  
  materials:
    purple:
      ambient: [0.2, 0.2, 0.2, 1.0]
      diffuse: [0.7, 0.5, 0.8, 1.0]
      specular: [0.5, 0.5, 0.5, 1.0]
      shininess: 100
    orange:
      ambient: [1.0, 0.5, 0.32, 1.0]
      diffuse: [1.0, 0.5, 0.32, 1.0]
      specular: [0.5, 0.5, 0.5, 1.0]
      shininess: 32

  # list of objects to be rendered
  objects:
    example:
      file: "resources/models/maca.byu"
      scale: 1
      position: [-200, 400, -90.5]
      material: "purple"
  
    example2:
      file: "resources/models/vaso.byu"
      scale: 1
      position: [145, 400, -80.5]
      material: "orange"